---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: "v1.33.0"
controlPlaneEndpoint: "{{ control_plane_endpoint }}" 
networking:
  serviceSubnet: "{{ kubeadm.service_cidr }}"
  podSubnet: "{{ kubeadm.pod_network_cidr }}"
  dnsDomain: "cluster.local"
apiServer:
  extraArgs:
    - name: "authorization-mode"
      value: "Node,RBAC"
  certSANs:
    - "{{ hostvars['k1']['ansible_host'] }}"
    - "{{ hostvars['k2']['ansible_host'] }}"
    - "{{ hostvars['k3']['ansible_host'] }}"
    - "{{ vip }}"
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
nodeRegistration:
  taints: []
  criSocket: "unix:///var/run/containerd/containerd.sock"
